# Generated by Django 3.2.25 on 2026-05-10 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_myuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_id', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('usuario_bd', models.CharField(max_length=80)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalle', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Auditoria de matricula',
                'verbose_name_plural': 'Auditoria de matriculas',
                'db_table': 'AUDITORIA_MATRICULAS',
                'ordering': ['-fecha_evento'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('creditos', models.IntegerField()),
                ('cupo_maximo', models.IntegerField()),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'CURSOS',
                'ordering': ['codigo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('especialidad', models.CharField(max_length=120)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'DOCENTES',
                'ordering': ['apellidos', 'nombres'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'ESTUDIANTES',
                'ordering': ['apellidos', 'nombres'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(default='MATRICULADO', max_length=20)),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'db_table': 'MATRICULAS',
                'ordering': ['-fecha_matricula'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
