-- ================================================================
-- PROYECTO FINAL - BASES DE DATOS CON ORACLE 18c XE
-- Sistema: Gestión académica de una institución educativa
-- Ejecutar conectado como SYS o SYSTEM en el servicio XEPDB1.
-- Ejemplo SQL*Plus:
-- sqlplus sys/Oracle123@//localhost:1521/XEPDB1 as sysdba
-- @scripts/01_crear_base_oracle_academico.sql
-- ================================================================

SET SERVEROUTPUT ON;
SET DEFINE OFF;

PROMPT ================================================================
PROMPT 1. Creación de tablespace, roles y usuarios
PROMPT ================================================================

BEGIN
	EXECUTE IMMEDIATE 'DROP USER SISTEMA_ACADEMICO_CONSULTA CASCADE';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -1918 THEN
			RAISE;
		END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP USER SISTEMA_ACADEMICO_APP CASCADE';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -1918 THEN
			RAISE;
		END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP ROLE ROL_ACADEMICO_ADMIN';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -1919 THEN
			RAISE;
		END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP ROLE ROL_ACADEMICO_CONSULTA';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -1919 THEN
			RAISE;
		END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLESPACE ACADEMICO_TS INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -959 THEN
			RAISE;
		END IF;
END;
/

CREATE TABLESPACE ACADEMICO_TS
DATAFILE 'C:\app\andro\product\18.0.0\oradata\XE\XEPDB1\academico01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 20M MAXSIZE 500M;

CREATE ROLE ROL_ACADEMICO_ADMIN;
CREATE ROLE ROL_ACADEMICO_CONSULTA;

CREATE USER SISTEMA_ACADEMICO_APP IDENTIFIED BY Academico123
DEFAULT TABLESPACE ACADEMICO_TS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON ACADEMICO_TS;

CREATE USER SISTEMA_ACADEMICO_CONSULTA IDENTIFIED BY Consulta123
DEFAULT TABLESPACE ACADEMICO_TS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO SISTEMA_ACADEMICO_APP;
GRANT CREATE TABLE TO SISTEMA_ACADEMICO_APP;
GRANT CREATE VIEW TO SISTEMA_ACADEMICO_APP;
GRANT CREATE SEQUENCE TO SISTEMA_ACADEMICO_APP;
GRANT CREATE PROCEDURE TO SISTEMA_ACADEMICO_APP;
GRANT CREATE TRIGGER TO SISTEMA_ACADEMICO_APP;
GRANT CREATE SESSION TO SISTEMA_ACADEMICO_CONSULTA;

GRANT ROL_ACADEMICO_ADMIN TO SISTEMA_ACADEMICO_APP;
GRANT ROL_ACADEMICO_CONSULTA TO SISTEMA_ACADEMICO_CONSULTA;

ALTER SESSION SET CURRENT_SCHEMA = SISTEMA_ACADEMICO_APP;

PROMPT ================================================================
PROMPT 2. Creación de secuencias
PROMPT ================================================================

CREATE SEQUENCE SEQ_ESTUDIANTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DOCENTES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CURSOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATRICULAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDITORIA_MATRICULAS START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT ================================================================
PROMPT 3. Creación de tablas y relaciones
PROMPT ================================================================

CREATE TABLE ESTUDIANTES
(
	ID NUMBER(10) NOT NULL,
	DOCUMENTO VARCHAR2(20) NOT NULL,
	NOMBRES VARCHAR2(100) NOT NULL,
	APELLIDOS VARCHAR2(100) NOT NULL,
	CORREO VARCHAR2(150) NOT NULL,
	TELEFONO VARCHAR2(20),
	FECHA_NACIMIENTO DATE NOT NULL,
	FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
	ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
	CONSTRAINT PK_ESTUDIANTES PRIMARY KEY (ID),
	CONSTRAINT UQ_ESTUDIANTES_DOCUMENTO UNIQUE (DOCUMENTO),
	CONSTRAINT UQ_ESTUDIANTES_CORREO UNIQUE (CORREO),
	CONSTRAINT CK_ESTUDIANTES_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE DOCENTES
(
	ID NUMBER(10) NOT NULL,
	DOCUMENTO VARCHAR2(20) NOT NULL,
	NOMBRES VARCHAR2(100) NOT NULL,
	APELLIDOS VARCHAR2(100) NOT NULL,
	CORREO VARCHAR2(150) NOT NULL,
	ESPECIALIDAD VARCHAR2(120) NOT NULL,
	ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
	CONSTRAINT PK_DOCENTES PRIMARY KEY (ID),
	CONSTRAINT UQ_DOCENTES_DOCUMENTO UNIQUE (DOCUMENTO),
	CONSTRAINT UQ_DOCENTES_CORREO UNIQUE (CORREO),
	CONSTRAINT CK_DOCENTES_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE CURSOS
(
	ID NUMBER(10) NOT NULL,
	CODIGO VARCHAR2(20) NOT NULL,
	NOMBRE VARCHAR2(120) NOT NULL,
	CREDITOS NUMBER(2) NOT NULL,
	CUPO_MAXIMO NUMBER(4) NOT NULL,
	DOCENTE_ID NUMBER(10) NOT NULL,
	ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
	CONSTRAINT PK_CURSOS PRIMARY KEY (ID),
	CONSTRAINT UQ_CURSOS_CODIGO UNIQUE (CODIGO),
	CONSTRAINT FK_CURSOS_DOCENTES FOREIGN KEY (DOCENTE_ID) REFERENCES DOCENTES(ID),
	CONSTRAINT CK_CURSOS_CREDITOS CHECK (CREDITOS BETWEEN 1 AND 6),
	CONSTRAINT CK_CURSOS_CUPO CHECK (CUPO_MAXIMO > 0),
	CONSTRAINT CK_CURSOS_ESTADO CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE MATRICULAS
(
	ID NUMBER(10) NOT NULL,
	ESTUDIANTE_ID NUMBER(10) NOT NULL,
	CURSO_ID NUMBER(10) NOT NULL,
	FECHA_MATRICULA DATE DEFAULT SYSDATE NOT NULL,
	NOTA_FINAL NUMBER(4,2),
	ESTADO VARCHAR2(20) DEFAULT 'MATRICULADO' NOT NULL,
	CONSTRAINT PK_MATRICULAS PRIMARY KEY (ID),
	CONSTRAINT FK_MATRICULAS_ESTUDIANTES FOREIGN KEY (ESTUDIANTE_ID) REFERENCES ESTUDIANTES(ID),
	CONSTRAINT FK_MATRICULAS_CURSOS FOREIGN KEY (CURSO_ID) REFERENCES CURSOS(ID),
	CONSTRAINT UQ_MATRICULA_ESTUDIANTE_CURSO UNIQUE (ESTUDIANTE_ID, CURSO_ID),
	CONSTRAINT CK_MATRICULAS_NOTA CHECK (NOTA_FINAL IS NULL OR NOTA_FINAL BETWEEN 0 AND 5),
	CONSTRAINT CK_MATRICULAS_ESTADO CHECK (ESTADO IN ('MATRICULADO', 'APROBADO', 'REPROBADO', 'CANCELADO'))
);

CREATE TABLE AUDITORIA_MATRICULAS
(
	ID NUMBER(10) NOT NULL,
	MATRICULA_ID NUMBER(10) NOT NULL,
	ACCION VARCHAR2(20) NOT NULL,
	USUARIO_BD VARCHAR2(80) DEFAULT USER NOT NULL,
	FECHA_EVENTO DATE DEFAULT SYSDATE NOT NULL,
	DETALLE VARCHAR2(500),
	CONSTRAINT PK_AUDITORIA_MATRICULAS PRIMARY KEY (ID)
);

PROMPT ================================================================
PROMPT 4. Creación de índices
PROMPT ================================================================

CREATE INDEX IDX_ESTUDIANTES_APELLIDOS ON ESTUDIANTES(APELLIDOS, NOMBRES);
CREATE INDEX IDX_DOCENTES_APELLIDOS ON DOCENTES(APELLIDOS, NOMBRES);
CREATE INDEX IDX_CURSOS_DOCENTE ON CURSOS(DOCENTE_ID);
CREATE INDEX IDX_MATRICULAS_ESTUDIANTE ON MATRICULAS(ESTUDIANTE_ID);
CREATE INDEX IDX_MATRICULAS_CURSO ON MATRICULAS(CURSO_ID);
CREATE INDEX IDX_AUDITORIA_MATRICULA ON AUDITORIA_MATRICULAS(MATRICULA_ID);

PROMPT ================================================================
PROMPT 5. Creación de vistas
PROMPT ================================================================

CREATE OR REPLACE VIEW VW_MATRICULAS_DETALLE AS
SELECT
	M.ID AS MATRICULA_ID,
	E.DOCUMENTO AS DOCUMENTO_ESTUDIANTE,
	E.NOMBRES || ' ' || E.APELLIDOS AS ESTUDIANTE,
	C.CODIGO AS CODIGO_CURSO,
	C.NOMBRE AS CURSO,
	C.CREDITOS,
	D.NOMBRES || ' ' || D.APELLIDOS AS DOCENTE,
	M.FECHA_MATRICULA,
	M.NOTA_FINAL,
	M.ESTADO
FROM MATRICULAS M
INNER JOIN ESTUDIANTES E ON E.ID = M.ESTUDIANTE_ID
INNER JOIN CURSOS C ON C.ID = M.CURSO_ID
INNER JOIN DOCENTES D ON D.ID = C.DOCENTE_ID;

CREATE OR REPLACE VIEW VW_RESUMEN_CURSOS AS
SELECT
	C.ID AS CURSO_ID,
	C.CODIGO,
	C.NOMBRE,
	C.CUPO_MAXIMO,
	COUNT(M.ID) AS TOTAL_MATRICULADOS,
	(C.CUPO_MAXIMO - COUNT(M.ID)) AS CUPOS_DISPONIBLES
FROM CURSOS C
LEFT JOIN MATRICULAS M ON M.CURSO_ID = C.ID AND M.ESTADO <> 'CANCELADO'
GROUP BY C.ID, C.CODIGO, C.NOMBRE, C.CUPO_MAXIMO;

PROMPT ================================================================
PROMPT 6. Procedimiento almacenado, función y trigger
PROMPT ================================================================

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_MATRICULA
(
	P_ESTUDIANTE_ID IN NUMBER,
	P_CURSO_ID IN NUMBER,
	P_MENSAJE OUT VARCHAR2
)
AS
	V_EXISTE NUMBER;
	V_CUPO_MAXIMO NUMBER;
	V_TOTAL_MATRICULADOS NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO V_EXISTE
	FROM MATRICULAS
	WHERE ESTUDIANTE_ID = P_ESTUDIANTE_ID
	  AND CURSO_ID = P_CURSO_ID
	  AND ESTADO <> 'CANCELADO';

	IF V_EXISTE > 0 THEN
		P_MENSAJE := 'El estudiante ya se encuentra matriculado en este curso.';
		RETURN;
	END IF;

	SELECT CUPO_MAXIMO
	INTO V_CUPO_MAXIMO
	FROM CURSOS
	WHERE ID = P_CURSO_ID
	  AND ESTADO = 'ACTIVO';

	SELECT COUNT(*)
	INTO V_TOTAL_MATRICULADOS
	FROM MATRICULAS
	WHERE CURSO_ID = P_CURSO_ID
	  AND ESTADO <> 'CANCELADO';

	IF V_TOTAL_MATRICULADOS >= V_CUPO_MAXIMO THEN
		P_MENSAJE := 'No hay cupos disponibles para este curso.';
		RETURN;
	END IF;

	INSERT INTO MATRICULAS
	(
		ID,
		ESTUDIANTE_ID,
		CURSO_ID,
		FECHA_MATRICULA,
		ESTADO
	)
	VALUES
	(
		SEQ_MATRICULAS.NEXTVAL,
		P_ESTUDIANTE_ID,
		P_CURSO_ID,
		SYSDATE,
		'MATRICULADO'
	);

	P_MENSAJE := 'Matrícula registrada correctamente.';
	COMMIT;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		P_MENSAJE := 'No se encontró el estudiante o el curso indicado.';
	WHEN OTHERS THEN
		ROLLBACK;
		P_MENSAJE := 'Error al registrar matrícula: ' || SQLERRM;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_CREDITOS_ESTUDIANTE
(
	P_ESTUDIANTE_ID IN NUMBER
)
RETURN NUMBER
AS
	V_TOTAL_CREDITOS NUMBER;
BEGIN
	SELECT NVL(SUM(C.CREDITOS), 0)
	INTO V_TOTAL_CREDITOS
	FROM MATRICULAS M
	INNER JOIN CURSOS C ON C.ID = M.CURSO_ID
	WHERE M.ESTUDIANTE_ID = P_ESTUDIANTE_ID
	  AND M.ESTADO <> 'CANCELADO';

	RETURN V_TOTAL_CREDITOS;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_MATRICULAS
AFTER INSERT OR UPDATE OR DELETE ON MATRICULAS
FOR EACH ROW
DECLARE
	V_ACCION VARCHAR2(20);
	V_MATRICULA_ID NUMBER(10);
	V_DETALLE VARCHAR2(500);
BEGIN
	IF INSERTING THEN
		V_ACCION := 'INSERT';
		V_MATRICULA_ID := :NEW.ID;
		V_DETALLE := 'Se registró matrícula del estudiante ' || :NEW.ESTUDIANTE_ID || ' en el curso ' || :NEW.CURSO_ID;
	ELSIF UPDATING THEN
		V_ACCION := 'UPDATE';
		V_MATRICULA_ID := :NEW.ID;
		V_DETALLE := 'Cambio de estado: ' || :OLD.ESTADO || ' -> ' || :NEW.ESTADO;
	ELSE
		V_ACCION := 'DELETE';
		V_MATRICULA_ID := :OLD.ID;
		V_DETALLE := 'Se eliminó matrícula del estudiante ' || :OLD.ESTUDIANTE_ID || ' en el curso ' || :OLD.CURSO_ID;
	END IF;

	INSERT INTO AUDITORIA_MATRICULAS
	(
		ID,
		MATRICULA_ID,
		ACCION,
		USUARIO_BD,
		FECHA_EVENTO,
		DETALLE
	)
	VALUES
	(
		SEQ_AUDITORIA_MATRICULAS.NEXTVAL,
		V_MATRICULA_ID,
		V_ACCION,
		USER,
		SYSDATE,
		V_DETALLE
	);
END;
/

PROMPT ================================================================
PROMPT 7. Inserción de datos de prueba
PROMPT ================================================================

INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010001', 'Laura', 'Martínez', 'laura.martinez@institucion.edu', 'Bases de datos', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010002', 'Carlos', 'Gómez', 'carlos.gomez@institucion.edu', 'Programación', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010003', 'Diana', 'Torres', 'diana.torres@institucion.edu', 'Matemáticas', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010004', 'Andrés', 'Rojas', 'andres.rojas@institucion.edu', 'Redes', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010005', 'Paula', 'Ramírez', 'paula.ramirez@institucion.edu', 'Seguridad informática', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010006', 'Miguel', 'Herrera', 'miguel.herrera@institucion.edu', 'Ingeniería de software', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010007', 'Sofía', 'Castro', 'sofia.castro@institucion.edu', 'Estadística', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010008', 'Jorge', 'Medina', 'jorge.medina@institucion.edu', 'Arquitectura de software', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010009', 'Natalia', 'Vargas', 'natalia.vargas@institucion.edu', 'Sistemas operativos', 'ACTIVO');
INSERT INTO DOCENTES VALUES (SEQ_DOCENTES.NEXTVAL, '80010010', 'Fernando', 'Pérez', 'fernando.perez@institucion.edu', 'Analítica de datos', 'ACTIVO');

INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010001', 'Juan', 'Pérez', 'juan.perez@correo.com', '3001111111', DATE '2001-03-15', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010002', 'María', 'López', 'maria.lopez@correo.com', '3001111112', DATE '2000-07-20', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010003', 'Pedro', 'Sánchez', 'pedro.sanchez@correo.com', '3001111113', DATE '2002-01-10', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010004', 'Camila', 'García', 'camila.garcia@correo.com', '3001111114', DATE '2001-11-05', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010005', 'Santiago', 'Moreno', 'santiago.moreno@correo.com', '3001111115', DATE '1999-05-29', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010006', 'Valentina', 'Ruiz', 'valentina.ruiz@correo.com', '3001111116', DATE '2003-02-18', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010007', 'Daniel', 'Torres', 'daniel.torres@correo.com', '3001111117', DATE '2000-09-12', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010008', 'Daniela', 'Castillo', 'daniela.castillo@correo.com', '3001111118', DATE '2002-12-01', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010009', 'Luis', 'Romero', 'luis.romero@correo.com', '3001111119', DATE '1998-08-23', SYSDATE, 'ACTIVO');
INSERT INTO ESTUDIANTES VALUES (SEQ_ESTUDIANTES.NEXTVAL, '10010010', 'Ana', 'Mendoza', 'ana.mendoza@correo.com', '3001111120', DATE '2001-04-09', SYSDATE, 'ACTIVO');

INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'BD101', 'Fundamentos de bases de datos', 3, 30, 1, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'PRG101', 'Programación orientada a objetos', 4, 28, 2, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'MAT101', 'Cálculo diferencial', 3, 35, 3, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'RED101', 'Redes de computadores', 3, 25, 4, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'SEG101', 'Seguridad informática', 3, 25, 5, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'ISW101', 'Ingeniería de software', 4, 30, 6, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'EST101', 'Estadística aplicada', 3, 32, 7, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'ARQ101', 'Arquitectura de software', 4, 22, 8, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'SO101', 'Sistemas operativos', 3, 26, 9, 'ACTIVO');
INSERT INTO CURSOS VALUES (SEQ_CURSOS.NEXTVAL, 'DAT101', 'Analítica de datos', 4, 24, 10, 'ACTIVO');

INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 1, 1, SYSDATE, 4.50, 'APROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 2, 2, SYSDATE, 4.10, 'APROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 3, 3, SYSDATE, 3.80, 'APROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 4, 4, SYSDATE, 2.90, 'REPROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 5, 5, SYSDATE, NULL, 'MATRICULADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 6, 6, SYSDATE, NULL, 'MATRICULADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 7, 7, SYSDATE, 4.80, 'APROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 8, 8, SYSDATE, 3.20, 'APROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 9, 9, SYSDATE, 2.50, 'REPROBADO');
INSERT INTO MATRICULAS VALUES (SEQ_MATRICULAS.NEXTVAL, 10, 10, SYSDATE, NULL, 'MATRICULADO');

COMMIT;

PROMPT ================================================================
PROMPT 8. Permisos finales de seguridad
PROMPT ================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON ESTUDIANTES TO ROL_ACADEMICO_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON DOCENTES TO ROL_ACADEMICO_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CURSOS TO ROL_ACADEMICO_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON MATRICULAS TO ROL_ACADEMICO_ADMIN;
GRANT SELECT ON AUDITORIA_MATRICULAS TO ROL_ACADEMICO_ADMIN;
GRANT SELECT ON VW_MATRICULAS_DETALLE TO ROL_ACADEMICO_ADMIN;
GRANT SELECT ON VW_RESUMEN_CURSOS TO ROL_ACADEMICO_ADMIN;
GRANT EXECUTE ON SP_REGISTRAR_MATRICULA TO ROL_ACADEMICO_ADMIN;
GRANT EXECUTE ON FN_TOTAL_CREDITOS_ESTUDIANTE TO ROL_ACADEMICO_ADMIN;

GRANT SELECT ON VW_MATRICULAS_DETALLE TO ROL_ACADEMICO_CONSULTA;
GRANT SELECT ON VW_RESUMEN_CURSOS TO ROL_ACADEMICO_CONSULTA;

REVOKE CREATE TABLE FROM SISTEMA_ACADEMICO_CONSULTA;

PROMPT ================================================================
PROMPT 9. Consultas de demostración
PROMPT ================================================================

PROMPT Consulta JOIN con detalle de matrículas
SELECT * FROM VW_MATRICULAS_DETALLE ORDER BY ESTUDIANTE;

PROMPT Consulta GROUP BY con cupos por curso
SELECT * FROM VW_RESUMEN_CURSOS ORDER BY CODIGO;

PROMPT Función: total de créditos del estudiante 1
SELECT FN_TOTAL_CREDITOS_ESTUDIANTE(1) AS TOTAL_CREDITOS FROM DUAL;

PROMPT Procedimiento: registrar matrícula de estudiante 1 en curso 2
DECLARE
	V_MENSAJE VARCHAR2(200);
BEGIN
	SP_REGISTRAR_MATRICULA(1, 2, V_MENSAJE);
	DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
END;
/

PROMPT Auditoría generada por trigger
SELECT * FROM AUDITORIA_MATRICULAS ORDER BY ID;

PROMPT ================================================================
PROMPT 10. Política de respaldo simulada
PROMPT ================================================================
PROMPT Política propuesta:a
PROMPT - Copia completa semanal de la base de datos.
PROMPT - Export diario del esquema SISTEMA_ACADEMICO_APP usando Data Pump.
PROMPT - Conservación mínima de 4 semanas de respaldos.
PROMPT Comando de ejemplo para ejecutar en CMD/PowerShell:
PROMPT expdp SISTEMA_ACADEMICO_APP/Academico123@//localhost:1521/XEPDB1 schemas=SISTEMA_ACADEMICO_APP directory=DATA_PUMP_DIR dumpfile=academico_%U.dmp logfile=academico_backup.log

PROMPT ================================================================
PROMPT Script finalizado correctamente
PROMPT ================================================================
